---
title: "look_at_data"
author: "Jasmine Grewal"
format: html
editor: visual
---

```{r}
#| label: loadlibrary

library(tidyverse)
library(sf)
#install.packages("mapview")
library(mapview)
```

```{r}
#|label: loaddata

read.csv("data/C148.csv") -> C148_data
C148_summary <-  C148_data |>
  add_column(Indv_ID = "C148") |>
  rename(dtUTC = "Date",
         lat = "Latitude",
         lon = "Longitude") |>
  summarise(Indv_ID, lat, lon, dtUTC)

read.csv("data/C172.csv") -> C172_data
C172_summary <- C172_data |>
  add_column(Indv_ID = "C172") |>
  rename(dtUTC = "GPSTime") |>
  summarise(Indv_ID, lat, lon, dtUTC)

read.csv("data/C173.csv") -> C173_data
C173_summary <- C173_data |>
  add_column(Indv_ID = "C173") |>
  rename(dtUTC = "GPSTime") |>
  summarise(Indv_ID, lat, lon, dtUTC)

read.csv("data/C174.csv") -> C174_data
C174_summary <- C174_data |>
  add_column(Indv_ID = "C174") |>
  rename(dtUTC = "GPSTime") |>
  summarise(Indv_ID, lat, lon, dtUTC)

read.csv("data/C175.csv") -> C175_data
C175_summary <- C175_data |>
  add_column(Indv_ID = "C175") |>
  rename(dtUTC = "GPSTime") |>
  summarise(Indv_ID, lat, lon, dtUTC)

read.csv("data/C176.csv") -> C176_data
C176_summary <- C176_data |>
  add_column(Indv_ID = "C176") |>
  rename(dtUTC = "GPSTime") |>
  summarise(Indv_ID, lat, lon, dtUTC)

read.csv("data/C177.csv") -> C177_data
C177_summary <- C177_data |>
  add_column(Indv_ID = "C177") |>
  rename(dtUTC = "GPSTime") |>
  summarise(Indv_ID, lat, lon, dtUTC)

read.csv("data/C178.csv") -> C178_data
C178_summary <- C178_data |>
  add_column(Indv_ID = "C178") |>
  rename(dtUTC = "GPSTime") |>
  summarise(Indv_ID, lat, lon, dtUTC)

read.csv("data/C131_C171.csv") -> C131_C171_data
C131_C171_summary <- C131_C171_data |>
  summarise(Indv_ID, lat, lon, dtUTC)
```

```{r}
coyote_data <- rbind(C131_C171_summary,
                     C148_summary,
                     C172_summary,
                     C173_summary,
                     C174_summary,
                     C175_summary,
                     C176_summary,
                     C177_summary,
                     C178_summary) |>
  rename(Longitude = "lon", Latitude = "lat")

coyote_data_summary <- coyote_data |>
  group_by(Indv_ID) |>
  summarise(ID = "Indv_ID", total_fixes = n())

```

```{r}
data <- coyote_data 

data <- data[!is.na(data$Longitude) & !is.na(data$Latitude),]

data_sf <- st_as_sf(data, coords = c("Longitude", "Latitude"), crs = 4326)

mapview(zcol = "Indv_ID", data_sf, legend = F, cex = 3)
```

```{r}
data <- coyote_data |>
filter(Indv_ID == c("C133", "C139", "C145", "C146", "C151","C153", "C154", "C155", "C156", "C158", "C164", "C176"))
data <- data[!is.na(data$Longitude) & !is.na(data$Latitude),]

data_sf <- st_as_sf(data, coords = c("Longitude", "Latitude"), crs = 4326)

mapview(zcol = "Indv_ID", data_sf, legend = F, cex = 3)
```
```{r}
data <- coyote_data |>
filter(Indv_ID == c("C131", "C136", "C138", "C141", "C142", "C143", "C147", "C163", "C166",  "C168", "C174"))
data <- data[!is.na(data$Longitude) & !is.na(data$Latitude),]

data_sf <- st_as_sf(data, coords = c("Longitude", "Latitude"), crs = 4326)

mapview(zcol = "Indv_ID", data_sf, legend = F, cex = 3)
```
```{r}
data <- coyote_data |>
filter(Indv_ID == c("C132", "C135", "C140", "C148", "C157","C161", "C162", "C169", "C171", "C173", "C177", "C178"))
  
data <- data[!is.na(data$Longitude) & !is.na(data$Latitude),]

data_sf <- st_as_sf(data, coords = c("Longitude", "Latitude"), crs = 4326)

mapview(zcol = "Indv_ID", data_sf, legend = F, cex = 3)
```
```{r}
data <- coyote_data |>
filter(Indv_ID == c("C134", "C144", "C149", "C156", "C159","C160", "C165", "C167", "C170", "C172", "C175"))
data <- data[!is.na(data$Longitude) & !is.na(data$Latitude),]

data_sf <- st_as_sf(data, coords = c("Longitude", "Latitude"), crs = 4326)

mapview(zcol = "Indv_ID", data_sf, legend = F, cex = 3)
```

```{r}
data <- coyote_data |>
filter(Indv_ID == c("C170", "C171", "C172", "C173", "C174","C175", "C176", "C177"))
data <- data[!is.na(data$Longitude) & !is.na(data$Latitude),]

data_sf <- st_as_sf(data, coords = c("Longitude", "Latitude"), crs = 4326)

mapview(zcol = "Indv_ID", data_sf, legend = F, cex = 3)
```